# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officefile',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
