# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_officefile_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='officefile',
            name='dict_coor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='officefile',
            name='file',
            field=models.FileField(upload_to=b'', validators=[web.validators.validate_file_extension]),
        ),
    ]
