# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160511_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='officefile',
            name='max_coor',
            field=models.IntegerField(default=100),
        ),
    ]
