# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_officefile_max_coor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officefile',
            name='max_coor',
        ),
    ]
